#!/bin/bash
# PXDesign Installer for NVIDIA Blackwell (SM_120)
# Author: Generated by Gemini for manual PXDesign fix
# Date: December 17, 2025

set -e  # Exit on error

# --- Configuration ---
ENV_NAME="pxdesign"
PYTHON_VER="3.12"
CUDA_VER="cu128"
WORK_DIR="$HOME/PXDesign"

echo ">>> Starting Blackwell Installation Protocol..."
mkdir -p $WORK_DIR
cd $WORK_DIR

# 1. Create Conda Environment
echo ">>> Creating Conda Environment: $ENV_NAME..."
source $(conda info --base)/etc/profile.d/conda.sh
conda create -n $ENV_NAME python=$PYTHON_VER -y
conda activate $ENV_NAME

# 2. Install PyTorch Nightly (Blackwell Required)
echo ">>> Installing PyTorch Nightly for $CUDA_VER..."
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/$CUDA_VER

# 3. Install JAX & DeepSpeed (Modern Hardware Support)
echo ">>> Installing JAX and DeepSpeed..."
pip install -U "jax[cuda12]"
pip install deepspeed ninja

# 4. Install Common Dependencies (Preventing downgrade loops)
echo ">>> Installing Scientific Stack..."
pip install scipy biopython==1.86 einops tqdm pyyaml transformers pandas \
    natsort fire omegaconf joblib dm-haiku chex optax ml-collections \
    cuequivariance-torch cuequivariance-ops-torch-cu12

# 5. Install Protenix (Manual Fixes)
echo ">>> Cloning & Patching Protenix..."
if [ ! -d "Protenix" ]; then
    git clone -b dev_design https://github.com/bytedance/Protenix.git
fi
cd Protenix
# Patch 1: Remove Torch/Flash-Attn from requirements
sed -i '/torch/d' requirements.txt
sed -i '/flash-attn/d' requirements.txt
# Patch 2: Fix "IndexError: list index out of range" in extend_types.py
# We replace line 42 with a safe check logic using python to generate a temp patch file
cat <<EOF > patch_extend_types.py
import sys
path = "protenix/config/extend_types.py"
with open(path, 'r') as f:
    lines = f.readlines()
with open(path, 'w') as f:
    for line in lines:
        if "self.dtype = type(value[0])" in line:
            f.write("        if len(value) > 0:\n")
            f.write("            self.dtype = type(value[0])\n")
            f.write("        else:\n")
            f.write("            self.dtype = dtype\n")
        else:
            f.write(line)
EOF
python patch_extend_types.py
pip install --no-deps -e .
cd ..

# 6. Install PXDesign (Manual Fixes)
echo ">>> Cloning & Patching PXDesign..."
if [ ! -d "PXDesign" ]; then
    git clone https://github.com/bytedance/PXDesign.git
fi
cd PXDesign
sed -i '/torch/d' requirements.txt
sed -i '/protenix/d' requirements.txt
# Patch: Fix empty seeds list crash
sed -i 's/"seeds": ListValue(\[\], dtype=int)/"seeds": ListValue([42], dtype=int)/' pxdesign/configs/configs_infer.py
pip install --no-deps -e .
cd ..

# 7. Install PXDesignBench (Manual Fixes)
echo ">>> Cloning & Patching PXDesignBench..."
if [ ! -d "PXDesignBench" ]; then
    git clone https://github.com/bytedance/PXDesignBench.git
fi
cd PXDesignBench
# Downgrade Biotite specifically for Protenix legacy requirement
pip install biotite==1.0.1
# Patch: Fix JSON serialization of float32 in AF2 tools
# We inject the NumpyEncoder class and modify the json.dump calls
for file in "pxdbench/tools/af2/main_af2_complex.py" "pxdbench/tools/af2/main_af2_monomer.py"; do
    # Add imports if missing
    sed -i '1s/^/import numpy as np\nimport json\n/' $file
    # Add the Encoder Class after imports
    sed -i '/import json/a \
class NumpyEncoder(json.JSONEncoder):\
    def default(self, obj):\
        if isinstance(obj, np.integer):\
            return int(obj)\
        if isinstance(obj, np.floating):\
            return float(obj)\
        if isinstance(obj, np.ndarray):\
            return obj.tolist()\
        return super(NumpyEncoder, self).default(obj)\n' $file
    # Replace json.dump with cls=NumpyEncoder
    sed -i 's/json.dump(results, f)/json.dump(results, f, cls=NumpyEncoder)/' $file
done
pip install --no-deps -e .
cd ..

# 8. Install ColabDesign (JAX Fix)
echo ">>> Cloning & Patching ColabDesign..."
if [ ! -d "ColabDesign" ]; then
    git clone https://github.com/sokrypton/ColabDesign.git
fi
cd ColabDesign
# Patch: Fix JAX backend deprecation
cat <<EOF > colabdesign/shared/utils.py
import jax
import jax.numpy as jnp
import numpy as np
import jax.extend.backend

def clear_mem():
  try:
    backend = jax.extend.backend.get_backend()
  except:
    backend = jax.lib.xla_bridge.get_backend()
  for buf in backend.live_buffers():
    buf.delete()
EOF
pip install --no-deps -e .
cd ..

echo ">>> Downloading Weights (This may take time)..."
cd PXDesign
bash download_tool_weights.sh

echo "=========================================================="
echo "  INSTALLATION COMPLETE"
echo "  Environment: $ENV_NAME"
echo ""
echo "  To run a job, use the flags below to disable incompatible kernels:"
echo "  pxdesign pipeline -i <INPUT.yaml> -o <OUT_DIR> --N_sample 1 --dtype bf16 --use_fast_ln False --use_deepspeed_evo_attention False"
echo "=========================================================="

